name: "CI"
on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    permissions:
      contents: write

    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Deploy to web
        run: |
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          npm run deploy
         env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
